sudo: required

language: bash

services:
  - docker

before_install:
  - docker build -t $DOCKER_USERNAME/ai-station .
  - docker images
  - docker run -it $DOCKER_USERNAME/ai-station zsh -c 'ais --version'
  - docker run -it $DOCKER_USERNAME/ai-station zsh -c 'ais init --name dummy_repo --author dummy_author && tree dummy_repo'

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
