sudo: required

language: bash

services:
  - docker

before_install:
  - docker build -t $DOCKER_USERNAME/{{ project_name }} .
  - docker images
  - docker run -it $DOCKER_USERNAME/{{ project_name }} /bin/bash -c 'ais --version'
  - docker run -it -e CODECOV_TOKEN=$CODECOV_TOKEN $DOCKER_USERNAME/{{ project_name }} /bin/bash -c 'ais tests'
